-- task_2.sql
-- PostgreSQL DDL for alx_book_store

CREATE SCHEMA IF NOT EXISTS alx_book_store;
SET search_path TO alx_book_store, public;

CREATE TABLE IF NOT EXISTS Authors (
  AuthorID SERIAL PRIMARY KEY,
  AuthorName VARCHAR(215) NOT NULL
);

CREATE TABLE IF NOT EXISTS Books (
  BookID SERIAL PRIMARY KEY,
  Title VARCHAR(130) NOT NULL,
  AuthorID INT NOT NULL REFERENCES Authors(AuthorID),
  Price DOUBLE PRECISION NOT NULL,
  PublicationDate DATE
);

CREATE TABLE IF NOT EXISTS Customers (
  CustomerID SERIAL PRIMARY KEY,
  CustomerName VARCHAR(215) NOT NULL,
  Email VARCHAR(215) NOT NULL UNIQUE,
  Address TEXT
);

CREATE TABLE IF NOT EXISTS Orders (
  OrderID SERIAL PRIMARY KEY,
  CustomerID INT NOT NULL REFERENCES Customers(CustomerID),
  OrderDate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Order_Details (
  OrderDetailID SERIAL PRIMARY KEY,
  OrderID INT NOT NULL REFERENCES Orders(OrderID) ON DELETE CASCADE,
  BookID INT NOT NULL REFERENCES Books(BookID),
  Quantity DOUBLE PRECISION NOT NULL
);
